### ISSUE TITLE
File Encoding Not Specified

### ISSUE THREAD

**Issue by mjiggidy** [GraphicalCode/elonmusk-babyname-gen#2]
File encoding is not specified; fails to open text files under Windows:

`Traceback (most recent call last):
  File "D:\Development\_forked\elonmusk-babyname-gen\elon_name.py", line 49, in <module>
    mywin=MyWindow(window)
  File "D:\Development\_forked\elonmusk-babyname-gen\elon_name.py", line 11, in __init__
    self.schar, self.model = self.random_name(self.s, self.p)
  File "D:\Development\_forked\elonmusk-babyname-gen\elon_name.py", line 27, in random_name
    for x in special:
  File "C:\Program Files\Python38\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 4: character maps to <undefined>`

**Comment by mjiggidy** [comment]
Fixed in pull request #3

**Comment by GraphicalCode** [comment]
Fixed by completing the merge. Thanks!
